### ISSUE TITLE
Package is broken with latest Plots.jl release

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/VisualRegressionTests.jl#10]
My visual regression tests are outputting completely random images with the latest release of Plots.jl. Could you please help me fix this issue? What has changed recently in Plots.jl that could have caused this?

**Comment by juliohm** [comment]
This is what the tests are producing:

![screenshot from 2018-01-13 11-26-46](https://user-images.githubusercontent.com/3345261/34909394-c78355b0-f854-11e7-90c7-95896bd6d758.png)

**Comment by daschw** [comment]
Hm, that really looks weird. Could it be related to GR saving pngs with a higher resolution now (https://github.com/JuliaPlots/Plots.jl/pull/1318)?

**Comment by daschw** [comment]
If that's the case setting `ENV["PLOTS_TEST"] = "true"` in the tests code could help.

**Comment by juliohm** [comment]
I did run the tests with PyPlot, and can confirm the issue is GR specific.
