### ISSUE TITLE
No confirm dialog

### ISSUE THREAD

**Issue by gustaphe** [JuliaPlots/VisualRegressionTests.jl#39]
I don't know if this is a system problem or what, but when running the Plots VRTs, I get this popup but no confirm dialog. 

![image](https://github.com/JuliaPlots/VisualRegressionTests.jl/assets/6677110/7a5f2b2e-f880-4550-a0ab-0782934198be)

The terminal also gets a
```
** (julia:136057): WARNING **: 21:22:17.230: atk-bridge: get_device_events_reply: unknown signature
```
, not sure if related.

Any ideas?

I'm on Arch Linux, i3wm. Julia 1.9.

**Comment by t-bltg** [comment]
You can set `ENV["VISUAL_REGRESSION_TESTS_AUTO"] = true` before running Plots test suite (see [here](https://github.com/JuliaPlots/VisualRegressionTests.jl#bypass-gui-popup-and-replace-reference-files-automatically)) to bypass confirmation dialog, and automatically overwrite reference files.

**Comment by gustaphe** [comment]
The problem is I am then not presented with the difference, I'm just disabling the test. In this case I'm sure there's no real difference, but I wanted it logged that this is an existing problem (especially if someone can confirm or deny the OS connection).

**Comment by gustaphe** [comment]
Can no longer reproduce.
