### ISSUE TITLE
Code coverage in plot recipes

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/VisualRegressionTests.jl#6]
As reported on discourse, the plot recipe is not covered by the test suite:

https://discourse.julialang.org/t/how-to-test-plot-recipes/2648

**Comment by juliohm** [comment]
@tbreloff is there any workaround for increasing coverage?

**Comment by tbreloff** [comment]
Nope

**Comment by juliohm** [comment]
Is there any plan to fix this issue? Can you please elaborate on what is happening?

**Comment by juliohm** [comment]
This is not an issue anymore. Closing.
