### ISSUE TITLE
Visual regression tests pass locally but fail in PkgEvaluator.jl

### ISSUE THREAD

**Issue by juliohm** [JuliaPlots/VisualRegressionTests.jl#7]
All visual tests pass locally on my machine, but some of them fail in the Julia package system: http://pkg.julialang.org/logs/ImageQuilting_0.5.log

What can be the reason for the failure?

**Comment by juliohm** [comment]
@tbreloff can you please take a look at this?

**Comment by tbreloff** [comment]
No. sorry.

**Comment by juliohm** [comment]
You mean you are busy or you will not look into it at all?
